import type { Metadata } from "next";
import { inter, geistMono } from "@/libs/fonts";
import { cn } from "@/libs/cn";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "text-gray-12 dark:bg-gray-1 bg-white font-sans antialiased",
        inter.variable,
        geistMono.variable,
      )}
    >
      <body>{children}</body>
    </html>
  );
}
